-- Contribution app schema draft for the shared EMC database.
-- The code in /src/app/contributions expects these lowercase table names.

insert into emcroles (rolename)
select role_name
from (
  values ('contrib_user'), ('contrib_admin')
) as roles(role_name)
where not exists (
  select 1 from emcroles existing where lower(existing.rolename) = lower(roles.role_name)
);

create table if not exists contribfundtype (
  id bigint generated by default as identity primary key,
  name text not null unique,
  datecreated timestamptz not null default timezone('utc', now()),
  dateupdated timestamptz not null default timezone('utc', now())
);

create table if not exists contribtype (
  id bigint generated by default as identity primary key,
  name text not null unique,
  taxdeductable boolean not null,
  datecreated timestamptz not null default timezone('utc', now()),
  dateupdated timestamptz not null default timezone('utc', now())
);

create table if not exists contribcontribution (
  id bigint generated by default as identity primary key,
  memberid bigint not null references emcmember(id),
  datedeposited date not null,
  dateentered timestamptz not null default timezone('utc', now()),
  amount numeric(12, 2) not null check (amount >= 0),
  comments text null,
  checkno text null,
  contributorid bigint not null references emcmember(id),
  fundtypeid bigint not null references contribfundtype(id),
  contributiontypeid bigint not null references contribtype(id),
  datecreated timestamptz not null default timezone('utc', now()),
  dateupdated timestamptz not null default timezone('utc', now())
);

create table if not exists contribaccountregion (
  accountid bigint not null references emcaccounts(id) on delete cascade,
  countrycode text not null references emccountry(code),
  datecreated timestamptz not null default timezone('utc', now()),
  dateupdated timestamptz not null default timezone('utc', now()),
  primary key (accountid, countrycode)
);

create index if not exists idx_contribcontribution_memberid
  on contribcontribution (memberid);

create index if not exists idx_contribcontribution_datedeposited
  on contribcontribution (datedeposited);

create index if not exists idx_contribcontribution_contributorid
  on contribcontribution (contributorid);

insert into contribfundtype (name)
select value
from (
  values ('Cash'), ('Check')
) as seed(value)
where not exists (
  select 1 from contribfundtype existing where lower(existing.name) = lower(seed.value)
);

insert into contribtype (name, taxdeductable)
select seed.name, seed.taxdeductable
from (
  values
    ('Assistance', true),
    ('2nd Tithe', true),
    ('Feast Deposit', false),
    ('Holy Day Offering', true),
    ('Special Offering', true),
    ('Tithe/Offering', true),
    ('Administrative', false)
) as seed(name, taxdeductable)
where not exists (
  select 1 from contribtype existing where lower(existing.name) = lower(seed.name)
);
